### ISSUE TITLE
NoneType has no attribute 'strip'

### ISSUE THREAD

**Issue by denispasin** [jfboismenu/toggl2shotgun#1]
Traceback (most recent call last):
  File "shotgun2toggl.py", line 44, in <module>
    _main()
  File "shotgun2toggl.py", line 18, in _main
    (sg, sg_self), toggl = connect()
  File "/Users/pasind/Projects/toggl2shotgun/common.py", line 187, in connect
    return _log_into_sg(), _log_into_toggl()
  File "/Users/pasind/Projects/toggl2shotgun/common.py", line 90, in _log_into_sg
    site = _get_credential("Site", site)
  File "/Users/pasind/Projects/toggl2shotgun/common.py", line 38, in _get_credential
    while not cred_value.strip():
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by jfboismenu** [comment]
Fixed in https://github.com/jfboismenu/toggl2shotgun/commit/0f3f38513277ed579a5a26bc175f616cac6ef2f2
